/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtrlMenu;
import controlador.CtrlPedido;
import controlador.CtrlProducto;
import controlador.CtrlUsuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.ConsultasFactura;
import modelo.ConsultasMenu;
import modelo.ConsultasPedido;
import modelo.ConsultasProducto;
import modelo.ConsultasUsuario;
import modelo.Factura;
import modelo.Menu;
import modelo.Pedido;
import modelo.Producto;
import modelo.Usuario;

/**
 *
 * @author ASUS
 */
public class frmAmdinistrador extends javax.swing.JFrame {

    /**
     * Creates new form frmAmdinistrador
     */
    public frmAmdinistrador() {
        initComponents();
        iniciarMenuDelDia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClientes = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnMenuDia = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana De Administración");

        btnClientes.setText("GESTIONAR CLIENTES");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnMenu.setText("GESTIONAR MENÚ");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnProductos.setText("GESTIONAR PRODUCTOS");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnPedidos.setText("GESTONAR  PEDIDOS");
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });

        btnMenuDia.setText("MENU DEL DÍA");
        btnMenuDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuDiaActionPerformed(evt);
            }
        });

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProductos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPedidos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizar)
                            .addComponent(btnMenuDia))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClientes)
                    .addComponent(btnMenu))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProductos)
                    .addComponent(btnPedidos))
                .addGap(33, 33, 33)
                .addComponent(btnMenuDia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
            Menu modMenu = new Menu();
        ConsultasMenu modConsulMenu = new ConsultasMenu();
        frmMenu frmMenu= new frmMenu();

        CtrlMenu ctrl = new CtrlMenu(modMenu, modConsulMenu, frmMenu);

        ctrl.iniciar();
        frmMenu.setVisible(true);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        try {
            Pedido modPedido = new Pedido();
            ConsultasPedido modConsulPedido = new ConsultasPedido();
            frmPedido frmPedido = new frmPedido();
            Factura modFactura = new Factura();
            ConsultasFactura modConsulFactura = new ConsultasFactura();
            Usuario modUsuario = new Usuario();
            
            CtrlPedido ctrl = new CtrlPedido(modPedido, modConsulPedido, frmPedido, modFactura, modConsulFactura, modUsuario);
            
            ctrl.iniciar();
            frmPedido.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmAmdinistrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        try {                                            
            Usuario modUsu = new Usuario();
            ConsultasUsuario modConsulUsu = new ConsultasUsuario();
            frmUsuario frmUsu =new frmUsuario();
            try {
                frmUsu = new frmUsuario();
            } catch (SQLException ex) {
                Logger.getLogger(frmAmdinistrador.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            CtrlUsuario ctrl = new CtrlUsuario(modUsu, modConsulUsu, frmUsu);
            
            ctrl.iniciar();
            frmUsu.setVisible(true);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(frmAmdinistrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnMenuDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuDiaActionPerformed
      frmGestionarMenus menus = new frmGestionarMenus ();
        menus.setVisible(true);
        
    }//GEN-LAST:event_btnMenuDiaActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
   
        try {
            Producto modPro = new Producto();
            ConsultasProducto modConsulPro = new ConsultasProducto();
            frmProducto frmPro = new frmProducto();
            
            CtrlProducto ctrl = new CtrlProducto(modPro, modConsulPro, frmPro);
             
            ctrl.iniciar();
        } catch (SQLException ex) {
            Logger.getLogger(frmAmdinistrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
       iniciarMenuDelDia();
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAmdinistrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAmdinistrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAmdinistrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAmdinistrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAmdinistrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMenuDia;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnProductos;
    // End of variables declaration//GEN-END:variables

    private void iniciarMenuDelDia() {
   frmGestionarMenus menus = new frmGestionarMenus ();
        
        menus.setVisible(true);
        menus.btnCambiarMenu.setVisible(false);
        menus.cbxMenu1.setVisible(false);
        menus.cbxMenu2.setVisible(false);
        menus.cbxMenu3.setVisible(false);
        menus.cbxMenu4.setVisible(false);
        menus.cbxMenu5.setVisible(false);
        menus.txtIdMenu1.setVisible(false);
        menus.txtIdMenu2.setVisible(false);
        menus.txtIdMenu3.setVisible(false);
        menus.txtIdMenu4.setVisible(false);
        menus.txtIdMenu5.setVisible(false);
        
    }
}
