/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.ConexionDataBase;

/**
 *
 * @author ASUS
 */
public class frmPedido extends javax.swing.JFrame {

    /** Creates new form frmPedido */
    public frmPedido() throws SQLException {
        initComponents();
        lblClave.setEnabled(false);
        txtClave.setEnabled(false);
        lblClavePedido.setEnabled(false);
        txtClaveFactura.setEnabled(false);
        try (Connection con = ConexionDataBase.getConection();) {
            PreparedStatement ps;
            ResultSet rs = null;
            String sql = "SELECT nombre FROM menu";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            cbxMenu.addItem("Selecciona Menu");

            while (rs.next()) {
                cbxMenu.addItem(rs.getString("nombre"));
            }
            

        } catch (Exception e) {
            throw  new SQLException(e);
        }
        try (Connection con = ConexionDataBase.getConection();) {
            PreparedStatement ps;
            ResultSet rs = null;
            String sql = "SELECT clave FROM pedido";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            cbxBuscarClave.addItem("Selecciona Clave");

            while (rs.next()) {
                cbxBuscarClave.addItem(rs.getString("clave"));
            }
            

        } catch (Exception e) {
            throw  new SQLException(e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdFacturar = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaPedidos = new javax.swing.JTable();
        lblIdFactura = new javax.swing.JLabel();
        lblNombreFactura = new javax.swing.JLabel();
        lblTipoDocFactura = new javax.swing.JLabel();
        lblNumDocFactura = new javax.swing.JLabel();
        lblValorFactura = new javax.swing.JLabel();
        lblEstadoFactura = new javax.swing.JLabel();
        txtIdFactura = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNumDocumento = new javax.swing.JTextField();
        txtValorFactura = new javax.swing.JTextField();
        txtEstadoFactura = new javax.swing.JTextField();
        lblClavePedido = new javax.swing.JLabel();
        txtClaveFactura = new javax.swing.JTextField();
        btnFacturar = new javax.swing.JButton();
        btnModificarFac = new javax.swing.JButton();
        btnEliminarFac = new javax.swing.JButton();
        btnLimpiarFac = new javax.swing.JButton();
        btnBuscarUsuario = new javax.swing.JButton();
        lblPedido = new javax.swing.JLabel();
        cbxTipoDocumento = new javax.swing.JComboBox<>();
        cbxFacturas = new javax.swing.JComboBox<>();
        btnBuscarFactura = new javax.swing.JButton();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        cbxMenu = new javax.swing.JComboBox<>();
        txtValorTotal = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        cbxBuscarClave = new javax.swing.JComboBox<>();
        spnCantidadMenu = new javax.swing.JSpinner();
        lblUltimosPedidos = new javax.swing.JLabel();
        lblClave = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        cbxEstado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablaMenus = new javax.swing.JTable();
        btnAgregarAlPedido = new javax.swing.JButton();
        btnEliminarDelPedido = new javax.swing.JButton();
        btnFacturarPedido = new javax.swing.JButton();

        jdFacturar.setTitle("Facturar");

        jTablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane2.setViewportView(jTablaPedidos);

        lblIdFactura.setText("id:");

        lblNombreFactura.setText("Nombre");

        lblTipoDocFactura.setText("Tipo Documento");

        lblNumDocFactura.setText("Número Documento:");

        lblValorFactura.setText("Valor Total:");

        lblEstadoFactura.setText("Estado");

        lblClavePedido.setText("Clave Pedido");

        btnFacturar.setText("FACTURAR");

        btnModificarFac.setText("MODIFICAR");

        btnEliminarFac.setText("ELIMINAR FACTURA");

        btnLimpiarFac.setText("LIMPIAR");

        btnBuscarUsuario.setText("BUSCAR");
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });

        lblPedido.setText("Pedido:");

        cbxTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Documento", "Cédula de Ciudadanía", "Tarjeta Identidad" }));

        btnBuscarFactura.setText("BUSCAR FACTURA");

        lblApellidos.setText("Apellidos");

        javax.swing.GroupLayout jdFacturarLayout = new javax.swing.GroupLayout(jdFacturar.getContentPane());
        jdFacturar.getContentPane().setLayout(jdFacturarLayout);
        jdFacturarLayout.setHorizontalGroup(
            jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdFacturarLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdFacturarLayout.createSequentialGroup()
                        .addGroup(jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdFacturarLayout.createSequentialGroup()
                                .addComponent(btnFacturar)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificarFac)
                                .addGap(30, 30, 30)
                                .addComponent(btnEliminarFac)
                                .addGap(27, 27, 27)
                                .addComponent(btnLimpiarFac))
                            .addGroup(jdFacturarLayout.createSequentialGroup()
                                .addGroup(jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdFacturarLayout.createSequentialGroup()
                                        .addComponent(lblIdFactura)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIdFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(lblClavePedido)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtClaveFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(124, 124, 124))
                                    .addGroup(jdFacturarLayout.createSequentialGroup()
                                        .addGroup(jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNombreFactura)
                                            .addComponent(lblApellidos))
                                        .addGap(40, 40, 40)
                                        .addGroup(jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtApellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPedido)
                                    .addGroup(jdFacturarLayout.createSequentialGroup()
                                        .addComponent(cbxFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscarFactura)))))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(jdFacturarLayout.createSequentialGroup()
                        .addGroup(jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdFacturarLayout.createSequentialGroup()
                                    .addComponent(lblEstadoFactura)
                                    .addGap(72, 72, 72)
                                    .addComponent(txtEstadoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jdFacturarLayout.createSequentialGroup()
                                    .addGroup(jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdFacturarLayout.createSequentialGroup()
                                            .addComponent(lblNumDocFactura)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdFacturarLayout.createSequentialGroup()
                                            .addComponent(lblValorFactura)
                                            .addGap(47, 47, 47)))
                                    .addGroup(jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtValorFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jdFacturarLayout.createSequentialGroup()
                                            .addComponent(txtNumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnBuscarUsuario)))))
                            .addGroup(jdFacturarLayout.createSequentialGroup()
                                .addComponent(lblTipoDocFactura)
                                .addGap(28, 28, 28)
                                .addComponent(cbxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jdFacturarLayout.setVerticalGroup(
            jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdFacturarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdFactura)
                    .addComponent(txtIdFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClavePedido)
                    .addComponent(txtClaveFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreFactura)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdFacturarLayout.createSequentialGroup()
                        .addComponent(lblPedido)
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdFacturarLayout.createSequentialGroup()
                        .addGroup(jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidos)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoDocFactura)
                            .addComponent(cbxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumDocFactura)
                            .addComponent(txtNumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarUsuario))
                        .addGap(20, 20, 20)
                        .addGroup(jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorFactura)
                            .addComponent(txtValorFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoFactura)
                    .addComponent(txtEstadoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jdFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFacturar)
                    .addComponent(btnModificarFac)
                    .addComponent(btnEliminarFac)
                    .addComponent(btnLimpiarFac))
                .addContainerGap())
        );

        setResizable(false);

        lblId.setText("id:");

        lblMenu.setText("Menú Pedido:");

        lblCantidad.setText("Cantidad:");

        lblValorTotal.setText("Valor Total:");

        lblEstado.setText("Estado:");

        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
        });

        btnGuardar.setText("GUARDAR");

        btnModificar.setText("MODIFICAR");

        btnEliminar.setText("ELIMINAR");

        btnLimpiar.setText("LIMPIAR");

        btnBuscar.setText("BUSCAR");

        spnCantidadMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                spnCantidadMenuKeyPressed(evt);
            }
        });

        lblUltimosPedidos.setText("Últimos Pedidos:");

        lblClave.setText("Clave:");

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preparación", "Cancelado" }));

        jtablaMenus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Menu", "Cantidad", "Costo Unidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtablaMenus);

        btnAgregarAlPedido.setText("AGREGAR");

        btnEliminarDelPedido.setText("ELIMINAR DEL PEDIDO");

        btnFacturarPedido.setText("FACTURAR PEDIDO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValorTotal)
                                    .addComponent(lblEstado))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(btnEliminarDelPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMenu)
                                    .addComponent(lblCantidad)
                                    .addComponent(lblClave))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spnCantidadMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAgregarAlPedido))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(lblUltimosPedidos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbxBuscarClave, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscar)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblId)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbxMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 85, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(33, 33, 33)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFacturarPedido)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxBuscarClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar)
                            .addComponent(lblUltimosPedidos)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblId)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClave)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMenu)
                    .addComponent(cbxMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnCantidadMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantidad)
                            .addComponent(btnAgregarAlPedido))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorTotal)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstado)
                            .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarDelPedido)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnFacturarPedido))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
      txtId.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();

                // Verificar si la tecla pulsada no es un digito
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
                    e.consume();  // ignorar el evento de teclado
                }
            }
        });
        
    }//GEN-LAST:event_txtIdKeyPressed

    private void spnCantidadMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnCantidadMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_spnCantidadMenuKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmPedido().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frmPedido.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarAlPedido;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnBuscarFactura;
    public javax.swing.JButton btnBuscarUsuario;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnEliminarDelPedido;
    public javax.swing.JButton btnEliminarFac;
    public javax.swing.JButton btnFacturar;
    public javax.swing.JButton btnFacturarPedido;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnLimpiarFac;
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnModificarFac;
    public javax.swing.JComboBox<String> cbxBuscarClave;
    public javax.swing.JComboBox<String> cbxEstado;
    public javax.swing.JComboBox<String> cbxFacturas;
    public javax.swing.JComboBox<String> cbxMenu;
    public javax.swing.JComboBox<String> cbxTipoDocumento;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTablaPedidos;
    public javax.swing.JDialog jdFacturar;
    public javax.swing.JTable jtablaMenus;
    public javax.swing.JLabel lblApellidos;
    public javax.swing.JLabel lblCantidad;
    public javax.swing.JLabel lblClave;
    public javax.swing.JLabel lblClavePedido;
    public javax.swing.JLabel lblEstado;
    public javax.swing.JLabel lblEstadoFactura;
    public javax.swing.JLabel lblId;
    public javax.swing.JLabel lblIdFactura;
    public javax.swing.JLabel lblMenu;
    public javax.swing.JLabel lblNombreFactura;
    public javax.swing.JLabel lblNumDocFactura;
    public javax.swing.JLabel lblPedido;
    public javax.swing.JLabel lblTipoDocFactura;
    public javax.swing.JLabel lblUltimosPedidos;
    public javax.swing.JLabel lblValorFactura;
    public javax.swing.JLabel lblValorTotal;
    public javax.swing.JSpinner spnCantidadMenu;
    public javax.swing.JTextField txtApellidos;
    public javax.swing.JTextField txtClave;
    public javax.swing.JTextField txtClaveFactura;
    public javax.swing.JTextField txtEstadoFactura;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtIdFactura;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNumDocumento;
    public javax.swing.JTextField txtValorFactura;
    public javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables

}
